version: "3.3"
services:

  db:
    image: migasfree/db:0.4
    environment:
      - POSTGRES_CRON=${POSTGRES_CRON}
      - POSTGRES_HOST=${FQDN}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ALLOW_HOSTS=${POSTGRES_ALLOW_HOSTS}
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "/nfs-share/conf:/etc/migasfree-server"
      - "/nfs-share/dump:/var/migasfree/dump"
      - "/data:/var/lib/postgresql/data"
    deploy:
      placement:
        constraints: [node.hostname == manager1]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  server:
    image: migasfree/server:master
    environment:
      - FQDN=${FQDN}
      - TZ=${TZ}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "${MIGASFREE_PORT}:80"
    volumes:
      - "/nfs-share/conf:/etc/migasfree-server"
      - "/nfs-share/public:/var/migasfree/repo"
      - "/nfs-share/keys:/usr/share/migasfree-server"
    deploy:
      mode: global
      placement:
        constraints: [node.hostname != manager1]
      restart_policy:
        condition: on-failure
